spring:
  application:
    name: Quizzle
  profiles:
    active: dev
    include:
      - secret
  config:
    import: optional:file:.env[.properties]


openai:
  model: ${OPENAI_MODEL:gpt-3.5-turbo}
  api:
    key: ${OPENAI_API_KEY:dummy-api-key}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}

quizzle:
  messaging:
    provider: stomp
    room:
      provider: stomp
    chat:
      provider: redis
