spring:
  websocket:
    endpoint: /ws
    allowed-origins:
      - https://secret-fe.vercel.app
      - https://quizzle.p-e.kr

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com.ll.quizzle: INFO
    org.springframework.web.socket: INFO

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: never
    whitelabel:
      enabled: false

custom:
  site:
    cookieDomain: quizzle.p-e.kr
    frontUrl: "https://secret-fe.vercel.app"
    backUrl: "https://quizzle.p-e.kr"
    name: Quizzle
  cors:
    allowed-origins:
      - https://secret-fe.vercel.app
      - https://quizzle.p-e.kr

app:
  websocket:
    use-distributed-sessions: true
