spring:
  profiles:
    active: dev
    include:
      - secret
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ON_SECRET
            client-secret: ON_SECRET
            redirect-uri: "${custom.site.backUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
          kakao:
            client-id: ON_SECRET
            client-secret: ON_SECRET
            redirect-uri: "${custom.site.backUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

quizzle:
  messaging:
    provider: stomp
    room:
      provider: stomp
    chat:
      provider: redis

app:
  oauth2:
    authorizedRedirectUris: http://localhost:3000/oauth/callback

custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:8080"
  prod:
    cookieDomain: NEED_TO_INPUT
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: Quizzle
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080