spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect

  websocket:
    endpoint: /ws
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://127.0.0.1:3000
      - http://127.0.0.1:5173
      - chrome-extension://*

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    com.ll.quizzle: DEBUG
    org.springframework.web.socket: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: always
    include-message: always

custom:
  site:
    cookieDomain: localhost
    frontUrl: "http://localhost:5173"
    backUrl: "http://localhost:8080"
    name: Quizzle
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:8080
